# Generated by Django 6.0.1 on 2026-01-29 17:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Rule Title')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True, verbose_name='URL Slug')),
                ('description', models.TextField(verbose_name='Rule Description')),
                ('rule_type', models.CharField(choices=[('rule', 'Rule'), ('regulation', 'Regulation'), ('policy', 'Policy'), ('procedure', 'Procedure'), ('guideline', 'Guideline')], default='rule', max_length=20, verbose_name='Type')),
                ('user_type', models.CharField(choices=[('all', 'All Users'), ('employee', 'Employees Only'), ('supervisor', 'Supervisors Only'), ('admin', 'Admins Only'), ('employee_supervisor', 'Employees & Supervisors')], default='all', max_length=20, verbose_name='Visible To')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='Priority Level')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Category')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags (e.g., attendance,safety,policies)', max_length=500, null=True)),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Is Mandatory?')),
                ('requires_acknowledgment', models.BooleanField(default=False, verbose_name='Requires User Acknowledgment?')),
                ('effective_date', models.DateField(default=django.utils.timezone.now, verbose_name='Effective Date')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Expiration Date')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True, verbose_name='Last Reviewed Date')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rules', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('parent_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='rulesApp.rule', verbose_name='Parent Rule')),
            ],
            options={
                'verbose_name': 'Rule/Regulation',
                'verbose_name_plural': 'Rules & Regulations',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RuleAcknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('acknowledged', 'Acknowledged'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Acknowledgment Date')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='User Comments')),
                ('device_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Device Information')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgments', to='rulesApp.rule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_acknowledgments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rule Acknowledgment',
                'verbose_name_plural': 'Rule Acknowledgments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RuleAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='rules/attachments/%Y/%m/%d/', verbose_name='Attachment File')),
                ('file_name', models.CharField(max_length=255, verbose_name='File Name')),
                ('file_type', models.CharField(choices=[('document', 'Document'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], default='document', max_length=20, verbose_name='File Type')),
                ('file_size', models.PositiveIntegerField(verbose_name='File Size (bytes)')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Attachment Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='rulesApp.rule')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Rule Attachment',
                'verbose_name_plural': 'Rule Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['status', 'rule_type'], name='rulesApp_ru_status_993dde_idx'),
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['user_type', 'status'], name='rulesApp_ru_user_ty_dafbf2_idx'),
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['category', 'priority'], name='rulesApp_ru_categor_e4544d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ruleacknowledgment',
            unique_together={('user', 'rule')},
        ),
    ]
