# Generated by Django 6.0.1 on 2026-01-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ruleacknowledgment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ruleacknowledgment',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='ruleacknowledgment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ruleattachment',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='ruleattachment',
            name='uploaded_by',
        ),
        migrations.AlterModelOptions(
            name='rule',
            options={'ordering': ['-created_at'], 'verbose_name': 'Rule', 'verbose_name_plural': 'Rules'},
        ),
        migrations.RemoveIndex(
            model_name='rule',
            name='rulesApp_ru_status_993dde_idx',
        ),
        migrations.RemoveIndex(
            model_name='rule',
            name='rulesApp_ru_user_ty_dafbf2_idx',
        ),
        migrations.RemoveIndex(
            model_name='rule',
            name='rulesApp_ru_categor_e4544d_idx',
        ),
        migrations.AlterField(
            model_name='rule',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule_type',
            field=models.CharField(choices=[('rule', 'Rule'), ('regulation', 'Regulation')], default='rule', max_length=20),
        ),
        migrations.AlterField(
            model_name='rule',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='rule',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rule',
            name='user_type',
            field=models.CharField(choices=[('all', 'All Users'), ('employee', 'Employees Only'), ('supervisor', 'Supervisors Only'), ('both', 'Employees & Supervisors')], default='all', max_length=20),
        ),
        migrations.DeleteModel(
            name='RuleAcknowledgment',
        ),
        migrations.DeleteModel(
            name='RuleAttachment',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='category',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='effective_date',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='is_mandatory',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='last_reviewed',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='parent_rule',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='requires_acknowledgment',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='version',
        ),
    ]
