# Generated by Django 5.2.10 on 2026-02-13 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOffChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason for the day-off change request')),
                ('current_day_off', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday'), ('none', 'No Day Off')], help_text='Current day off of the employee', max_length=20)),
                ('requested_day_off', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday'), ('none', 'No Day Off')], help_text='Requested new day off', max_length=20)),
                ('effective_from', models.DateField(help_text='Date when the change should take effect if approved')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, help_text='Timestamp when request was approved/rejected', null=True)),
                ('approval_notes', models.TextField(blank=True, help_text='Notes from approver (reason for rejection, etc.)', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='Timestamp when request was cancelled', null=True)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Exact time the request was sent')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Manager or admin who approved/rejected the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_day_off_requests', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, help_text='User who cancelled the request (employee themselves)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_day_off_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Employee making the request', on_delete=django.db.models.deletion.CASCADE, related_name='day_off_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Day Off Change Request',
                'verbose_name_plural': 'Day Off Change Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='requestApp__user_id_830ec9_idx'), models.Index(fields=['status', 'created_at'], name='requestApp__status_f5572c_idx'), models.Index(fields=['effective_from'], name='requestApp__effecti_b78c78_idx')],
            },
        ),
    ]
