# Generated by Django 5.2.10 on 2026-02-11 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_end_reminder', models.BooleanField(default=True)),
                ('task_end_reminder_minutes', models.IntegerField(default=5, help_text='Minutes before task end')),
                ('upcoming_task_alert', models.BooleanField(default=True)),
                ('task_missed_alerts', models.BooleanField(default=True, help_text='Receive alerts for missed tasks')),
                ('new_assignment_notification', models.BooleanField(default=True, verbose_name='New Assignments')),
                ('assignment_modification_notification', models.BooleanField(default=True, verbose_name='Assignment Modifications')),
                ('assignment_completion_notification', models.BooleanField(default=True, verbose_name='Assignment Completions')),
                ('system_alerts', models.BooleanField(default=True, verbose_name='System Alerts')),
                ('performance_alerts', models.BooleanField(default=True, verbose_name='Performance Alerts')),
                ('web_notifications', models.BooleanField(default=True, verbose_name='Web Notifications')),
                ('email_notifications', models.BooleanField(default=False, verbose_name='Email Notifications')),
                ('dnd_enabled', models.BooleanField(default=False, verbose_name='Do Not Disturb')),
                ('dnd_start_time', models.TimeField(blank=True, null=True, verbose_name='DND Start Time')),
                ('dnd_end_time', models.TimeField(blank=True, null=True, verbose_name='DND End Time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('task_assignment_create', 'Task Assignment Created'), ('task_assignment_update', 'Task Assignment Updated'), ('task_assignment_complete', 'Task Assignment Completed'), ('task_missed_alert', 'Task Missed Alert'), ('task_end_reminder', 'Task End Reminder'), ('upcoming_task_alert', 'Upcoming Task Alert'), ('system_alert', 'System Alert'), ('performance_alert', 'Performance Alert')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=255, null=True)),
                ('action_text', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When notification becomes irrelevant', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', 'created_at'], name='notificatio_user_id_58247f_idx'), models.Index(fields=['notification_type', 'created_at'], name='notificatio_notific_ddbc1e_idx'), models.Index(fields=['user', 'notification_type', 'is_read'], name='notificatio_user_id_669a85_idx')],
            },
        ),
    ]
