# Generated by Django 5.2.10 on 2026-02-11 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departmentApp', '0002_initial'),
        ('taskApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssignmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_days', models.CharField(blank=True, help_text='Comma-separated days (0=Sunday, 1=Monday, etc.)', max_length=50, null=True)),
                ('assign_to_all_department', models.BooleanField(default=False, help_text='Assign to all employees in department')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_templates_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departmentApp.department')),
                ('specific_users', models.ManyToManyField(blank=True, help_text='Specific users to assign (if not all department)', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskApp.task')),
            ],
            options={
                'verbose_name': 'Task Assignment Template',
                'verbose_name_plural': 'Task Assignment Templates',
            },
        ),
        migrations.CreateModel(
            name='TaskOverload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overload_date', models.DateField()),
                ('additional_employees_needed', models.IntegerField(default=1, help_text='Additional employees needed beyond normal assignment')),
                ('time_slot_start', models.TimeField(blank=True, help_text='Specific time slot start (optional)', null=True)),
                ('time_slot_end', models.TimeField(blank=True, help_text='Specific time slot end (optional)', null=True)),
                ('reason', models.TextField(help_text='Reason for overload')),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overloads_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_overloads', to='departmentApp.department')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overloads', to='taskApp.task')),
            ],
            options={
                'verbose_name': 'Task Overload',
                'verbose_name_plural': 'Task Overloads',
                'ordering': ['-overload_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateField(help_text='Date of the assignment')),
                ('start_time', models.DateTimeField(help_text='When employee should start this task')),
                ('end_time', models.DateTimeField(help_text='When employee should finish this task')),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('missed', 'Missed'), ('reassigned', 'Reassigned'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('sequence_order', models.IntegerField(default=1, help_text='Order of tasks for the day')),
                ('is_modified', models.BooleanField(default=False, help_text='True if assignment was manually modified')),
                ('modification_reason', models.TextField(blank=True, help_text='Reason for manual modification', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Store tracking data like sent reminders')),
                ('reminder_sent', models.BooleanField(default=False)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to='departmentApp.department')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_modified', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='taskApp.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Assignment',
                'verbose_name_plural': 'Task Assignments',
                'ordering': ['assignment_date', 'start_time', 'sequence_order'],
                'indexes': [models.Index(fields=['user', 'assignment_date', 'status'], name='taskAssignm_user_id_cf5740_idx'), models.Index(fields=['assignment_date', 'start_time'], name='taskAssignm_assignm_0dfcdc_idx'), models.Index(fields=['status', 'start_time'], name='taskAssignm_status_98ef88_idx'), models.Index(fields=['department', 'assignment_date'], name='taskAssignm_departm_7d799e_idx')],
                'unique_together': {('user', 'assignment_date', 'sequence_order')},
            },
        ),
    ]
