# Generated by Django 5.2.10 on 2026-02-12 07:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departmentApp', '0002_initial'),
        ('taskApp', '0001_initial'),
        ('taskAssignmentApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskassignment',
            options={'ordering': ['start_time', 'sequence_order'], 'verbose_name': 'Task Assignment', 'verbose_name_plural': 'Task Assignments'},
        ),
        migrations.RemoveIndex(
            model_name='taskassignment',
            name='taskAssignm_assignm_0dfcdc_idx',
        ),
        migrations.AlterUniqueTogether(
            name='taskassignment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='assignment_date',
            field=models.DateField(help_text='Date when the assignment was created/scheduled'),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='end_time',
            field=models.DateTimeField(help_text='When employee should finish this task (can be future date)'),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='sequence_order',
            field=models.IntegerField(default=1, help_text='Order of tasks for the day (only relevant if start/end on same day)'),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='start_time',
            field=models.DateTimeField(help_text='When employee should start this task (can be future date)'),
        ),
        migrations.AlterUniqueTogether(
            name='taskassignmenttemplate',
            unique_together={('department', 'task', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['start_time', 'end_time'], name='taskAssignm_start_t_9ea16a_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['user', 'status'], name='taskAssignm_user_id_eb1b4c_idx'),
        ),
    ]
