# Generated by Django 5.2.10 on 2026-02-10 11:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('user_login', 'User Login'), ('user_logout', 'User Logout'), ('user_registration', 'User Registration'), ('password_reset_request', 'Password Reset Request'), ('password_reset_complete', 'Password Reset Complete'), ('password_change', 'Password Change'), ('otp_request', 'OTP Request'), ('otp_verification', 'OTP Verification'), ('user_create', 'User Created'), ('user_update', 'User Updated'), ('user_delete', 'User Deleted'), ('user_activate', 'User Activated'), ('user_deactivate', 'User Deactivated'), ('user_status_change', 'User Status Changed'), ('profile_update', 'Profile Updated'), ('user_view', 'User Viewed'), ('users_list', 'Users List Viewed'), ('department_create', 'Department Created'), ('department_update', 'Department Updated'), ('department_delete', 'Department Deleted'), ('department_view', 'Department Viewed'), ('departments_list', 'Departments List Viewed'), ('contact_submission', 'Contact Form Submitted'), ('api_request', 'API Request'), ('api_error', 'API Error')], help_text='Type of activity performed', max_length=50)),
                ('status_code', models.CharField(choices=[('200', '200 - OK'), ('201', '201 - Created'), ('202', '202 - Accepted'), ('204', '204 - No Content'), ('400', '400 - Bad Request'), ('401', '401 - Unauthorized'), ('403', '403 - Forbidden'), ('404', '404 - Not Found'), ('409', '409 - Conflict'), ('422', '422 - Unprocessable Entity'), ('500', '500 - Internal Server Error'), ('502', '502 - Bad Gateway'), ('503', '503 - Service Unavailable')], default='200', help_text='HTTP status code returned by the system', max_length=3)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the activity', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the request', null=True)),
                ('device_type', models.CharField(blank=True, help_text='Type of device used (Mobile, Desktop, Tablet)', max_length=50, null=True)),
                ('browser', models.CharField(blank=True, help_text='Browser used', max_length=100, null=True)),
                ('operating_system', models.CharField(blank=True, help_text='Operating system used', max_length=100, null=True)),
                ('request_method', models.CharField(blank=True, help_text='HTTP method (GET, POST, PUT, DELETE, etc.)', max_length=10, null=True)),
                ('endpoint', models.CharField(blank=True, help_text='API endpoint accessed', max_length=255, null=True)),
                ('request_data', models.JSONField(blank=True, help_text='Request payload (sanitized - no sensitive data)', null=True)),
                ('response_data', models.JSONField(blank=True, help_text='Response data (sanitized - no sensitive data)', null=True)),
                ('related_user_id', models.IntegerField(blank=True, help_text='ID of user that was affected by this activity', null=True)),
                ('related_department_id', models.IntegerField(blank=True, help_text='ID of department that was affected by this activity', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Exact date and time when activity was performed')),
                ('duration_ms', models.IntegerField(blank=True, help_text='Duration of the request in milliseconds', null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the activity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='activityApp_created_fffeb4_idx'), models.Index(fields=['user', '-created_at'], name='activityApp_user_id_6deba7_idx'), models.Index(fields=['activity_type', '-created_at'], name='activityApp_activit_73d4f2_idx'), models.Index(fields=['status_code', '-created_at'], name='activityApp_status__26c30a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ActivitySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('activity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('total_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Summary',
                'verbose_name_plural': 'Activity Summaries',
                'ordering': ['-period_start'],
                'unique_together': {('period_type', 'period_start', 'user', 'activity_type')},
            },
        ),
    ]
