# Generated by Django 5.2.10 on 2026-02-13 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityApp', '0002_activity_related_assignment_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='related_dayoff_request_id',
            field=models.IntegerField(blank=True, help_text='ID of day-off change request that was affected by this activity', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('user_login', 'User Login'), ('user_logout', 'User Logout'), ('user_registration', 'User Registration'), ('password_reset_request', 'Password Reset Request'), ('password_reset_complete', 'Password Reset Complete'), ('password_change', 'Password Change'), ('otp_request', 'OTP Request'), ('otp_verification', 'OTP Verification'), ('user_create', 'User Created'), ('user_update', 'User Updated'), ('user_delete', 'User Deleted'), ('user_activate', 'User Activated'), ('user_deactivate', 'User Deactivated'), ('user_status_change', 'User Status Changed'), ('profile_update', 'Profile Updated'), ('user_view', 'User Viewed'), ('users_list', 'Users List Viewed'), ('department_create', 'Department Created'), ('department_update', 'Department Updated'), ('department_delete', 'Department Deleted'), ('department_view', 'Department Viewed'), ('departments_list', 'Departments List Viewed'), ('department_employees_view', 'Department Employees View'), ('task_create', 'Task Created'), ('task_update', 'Task Updated'), ('task_delete', 'Task Deleted'), ('task_view', 'Task Viewed'), ('tasks_list', 'Tasks List Viewed'), ('task_view_by_name', 'Task Viewed By Name'), ('task_status_change', 'Task Status Changed'), ('task_assignment_create', 'Task Assignment Created'), ('task_assignment_update', 'Task Assignment Updated'), ('task_assignment_delete', 'Task Assignment Deleted'), ('task_assignment_view', 'Task Assignment Viewed'), ('task_assignments_list', 'Task Assignments List Viewed'), ('task_assignment_start', 'Task Assignment Started'), ('task_assignment_complete', 'Task Assignment Completed'), ('task_assignment_missed', 'Task Assignment Missed'), ('task_assignment_reassign', 'Task Assignment Reassigned'), ('task_assignment_modify', 'Task Assignment Modified'), ('task_assignment_priority_change', 'Task Assignment Priority Changed'), ('task_assignment_bulk_create', 'Task Assignment Bulk Created'), ('task_assignment_bulk_delete', 'Task Assignment Bulk Deleted'), ('task_assignment_bulk_update', 'Task Assignment Bulk Updated'), ('dayoff_request_create', 'Day-Off Request Created'), ('dayoff_request_update', 'Day-Off Request Updated'), ('dayoff_request_view', 'Day-Off Request Viewed'), ('dayoff_requests_list', 'Day-Off Requests List Viewed'), ('dayoff_request_approve', 'Day-Off Request Approved'), ('dayoff_request_reject', 'Day-Off Request Rejected'), ('dayoff_request_cancel', 'Day-Off Request Cancelled'), ('dayoff_request_delete', 'Day-Off Request Deleted'), ('dayoff_request_stats_view', 'Day-Off Request Statistics Viewed'), ('dayoff_request_bulk_view', 'Day-Off Requests Bulk Viewed'), ('notification_sent', 'Notification Sent'), ('notification_viewed', 'Notification Viewed'), ('notification_cleared', 'Notification Cleared'), ('contact_submission', 'Contact Form Submitted'), ('performance_view_own', 'Own Performance Viewed'), ('performance_view_user', 'User Performance Viewed'), ('performance_view_all', 'All Performances Viewed'), ('performance_view_department', 'Department Performance Viewed'), ('performance_view_departments', 'All Departments Performance Viewed'), ('performance_view_organization', 'Organization Performance Viewed'), ('api_request', 'API Request'), ('api_error', 'API Error')], help_text='Type of activity performed', max_length=50),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['related_dayoff_request_id', '-created_at'], name='activityApp_related_29c844_idx'),
        ),
    ]
