# Generated by Django 5.2.10 on 2026-02-13 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityApp', '0003_activity_related_dayoff_request_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='from_status',
            field=models.CharField(blank=True, help_text='Original status before transition (for status changes)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for status change or other actions', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='to_status',
            field=models.CharField(blank=True, help_text='New status after transition (for status changes)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='activitysummary',
            name='status_transition_counts',
            field=models.JSONField(blank=True, default=dict, help_text='JSON field storing counts of status transitions by type'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('user_login', 'User Login'), ('user_logout', 'User Logout'), ('user_registration', 'User Registration'), ('password_reset_request', 'Password Reset Request'), ('password_reset_complete', 'Password Reset Complete'), ('password_change', 'Password Change'), ('otp_request', 'OTP Request'), ('otp_verification', 'OTP Verification'), ('user_create', 'User Created'), ('user_update', 'User Updated'), ('user_delete', 'User Deleted'), ('user_activate', 'User Activated'), ('user_deactivate', 'User Deactivated'), ('user_status_change', 'User Status Changed'), ('profile_update', 'Profile Updated'), ('user_view', 'User Viewed'), ('users_list', 'Users List Viewed'), ('department_create', 'Department Created'), ('department_update', 'Department Updated'), ('department_delete', 'Department Deleted'), ('department_view', 'Department Viewed'), ('departments_list', 'Departments List Viewed'), ('department_employees_view', 'Department Employees View'), ('task_create', 'Task Created'), ('task_update', 'Task Updated'), ('task_delete', 'Task Deleted'), ('task_view', 'Task Viewed'), ('tasks_list', 'Tasks List Viewed'), ('task_view_by_name', 'Task Viewed By Name'), ('task_status_change', 'Task Status Changed'), ('task_assignment_create', 'Task Assignment Created'), ('task_assignment_update', 'Task Assignment Updated'), ('task_assignment_delete', 'Task Assignment Deleted'), ('task_assignment_view', 'Task Assignment Viewed'), ('task_assignments_list', 'Task Assignments List Viewed'), ('task_assignment_start', 'Task Assignment Started'), ('task_assignment_complete', 'Task Assignment Completed'), ('task_assignment_missed', 'Task Assignment Missed'), ('task_assignment_reassign', 'Task Assignment Reassigned'), ('task_assignment_modify', 'Task Assignment Modified'), ('task_assignment_priority_change', 'Task Assignment Priority Changed'), ('task_assignment_status_update', 'Task Assignment Status Updated'), ('task_assignment_status_scheduled_to_active', 'Task Assignment Status: Scheduled → Active'), ('task_assignment_status_scheduled_to_completed', 'Task Assignment Status: Scheduled → Completed'), ('task_assignment_status_scheduled_to_reassigned', 'Task Assignment Status: Scheduled → Reassigned'), ('task_assignment_status_scheduled_to_cancelled', 'Task Assignment Status: Scheduled → Cancelled'), ('task_assignment_status_active_to_completed', 'Task Assignment Status: Active → Completed'), ('task_assignment_status_active_to_reassigned', 'Task Assignment Status: Active → Reassigned'), ('task_assignment_status_active_to_cancelled', 'Task Assignment Status: Active → Cancelled'), ('task_assignment_status_missed_to_reassigned', 'Task Assignment Status: Missed → Reassigned'), ('task_assignment_status_missed_to_cancelled', 'Task Assignment Status: Missed → Cancelled'), ('task_assignment_bulk_create', 'Task Assignment Bulk Created'), ('task_assignment_bulk_delete', 'Task Assignment Bulk Deleted'), ('task_assignment_bulk_update', 'Task Assignment Bulk Updated'), ('task_assignment_missed_check', 'Task Assignment Missed Check Run'), ('task_assignment_status_transitions_view', 'Task Assignment Status Transitions Viewed'), ('dayoff_request_create', 'Day-Off Request Created'), ('dayoff_request_update', 'Day-Off Request Updated'), ('dayoff_request_view', 'Day-Off Request Viewed'), ('dayoff_requests_list', 'Day-Off Requests List Viewed'), ('dayoff_request_approve', 'Day-Off Request Approved'), ('dayoff_request_reject', 'Day-Off Request Rejected'), ('dayoff_request_cancel', 'Day-Off Request Cancelled'), ('dayoff_request_delete', 'Day-Off Request Deleted'), ('dayoff_request_stats_view', 'Day-Off Request Statistics Viewed'), ('dayoff_request_bulk_view', 'Day-Off Requests Bulk Viewed'), ('notification_sent', 'Notification Sent'), ('notification_viewed', 'Notification Viewed'), ('notification_cleared', 'Notification Cleared'), ('contact_submission', 'Contact Form Submitted'), ('performance_view_own', 'Own Performance Viewed'), ('performance_view_user', 'User Performance Viewed'), ('performance_view_all', 'All Performances Viewed'), ('performance_view_department', 'Department Performance Viewed'), ('performance_view_departments', 'All Departments Performance Viewed'), ('performance_view_organization', 'Organization Performance Viewed'), ('api_request', 'API Request'), ('api_error', 'API Error')], help_text='Type of activity performed', max_length=50),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['related_assignment_id', '-created_at'], name='activityApp_related_d04699_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['from_status', '-created_at'], name='activityApp_from_st_d14730_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['to_status', '-created_at'], name='activityApp_to_stat_a856bd_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['activity_type', 'from_status', 'to_status'], name='activityApp_activit_21e8f8_idx'),
        ),
        migrations.AddIndex(
            model_name='activitysummary',
            index=models.Index(fields=['period_type', 'period_start'], name='activityApp_period__f65c0f_idx'),
        ),
        migrations.AddIndex(
            model_name='activitysummary',
            index=models.Index(fields=['user', 'period_type', 'period_start'], name='activityApp_user_id_260135_idx'),
        ),
        migrations.AddIndex(
            model_name='activitysummary',
            index=models.Index(fields=['activity_type', 'period_type', 'period_start'], name='activityApp_activit_42fa11_idx'),
        ),
    ]
